minor: fix coveralls reporting

diff --git a/cov b/cov
--- a/cov
+++ b/cov
@@ -1,26 +1,28 @@
 #!/bin/bash
 DIST_ARCHIVES="$1"
-
 which lcov 1>/dev/null 2>&1
 if [ $? != 0 ]; then
     echo "$(basename $0) error: lcov: missing tool" 1>&2
     exit 1
 fi
 
-if [ ! $DIST_ARCHIVES ]; then
-    echo "$(basename $0) error: $DIST_ARCHIVES: missing archive" 1>&2
-    exit 1
-fi
+#if [ ! $DIST_ARCHIVES ]; then
+#    echo "$(basename $0) error: $DIST_ARCHIVES: missing archive" 1>&2
+#    exit 1
+#fi
 
-tar zxf $DIST_ARCHIVES
-srcdir=${DIST_ARCHIVES/.tar.gz}
-cd $srcdir
+set -x
+#tar zxf $DIST_ARCHIVES
+#srcdir=${DIST_ARCHIVES/.tar.gz}
+#cd $srcdir
 
 # Reconfigure with gcov support
-CFLAGS="-g -O0 --coverage" ./configure --disable-shared
-
 LCOV="lcov --rc lcov_branch_coverage=1"
+[ "x$GCOV" != "x" ] && LCOV="${LCOV} --gcov-tool $(which ${GCOV})"
+
 # Generate gcov output
+CFLAGS="-g -O0 --coverage" ./configure
+make clean
 make
 $LCOV --base-directory . --directory . --zerocounters -q
 make check
@@ -28,10 +30,10 @@ make check
 # Generate html report
 $LCOV --base-directory . --directory . -c  -o zedhat_test.info
 $LCOV --remove zedhat_test.info "/usr*" -o zedhat_test.info # remove output for external libraries
-rm -rf ../test_coverage
+#rm -rf test_coverage
 $LCOV --remove zedhat_test.info "*/tests/*" -o zedhat_test.info # remove test code
-genhtml -o ../test_coverage --rc lcov_branch_coverage=1 -t "zedhat test coverage" --num-spaces 4 zedhat_test.info
+genhtml -o test_coverage --rc lcov_branch_coverage=1 -t "zedhat test coverage" --num-spaces 4 zedhat_test.info
 
 # Clean work space
 #cd .. && rm -rf $srcdir
-echo "xdg-open test_coverage/index.html"
+echo "xdg-open ./test_coverage/index.html"
